AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Hello Go Lambda
Resources:
  CreateMemberFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: create-member
      Runtime: go1.x
      CodeUri: ./
      Events:
        MyTimeApi:
          Type: Api
          Properties:
            Path: /samudayik/member
            Method: POST
